# Generated by Django 3.1.7 on 2021-04-03 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("description", models.CharField(max_length=100, verbose_name="Description")),
                ("content", models.TextField(verbose_name="Text")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
