# Generated by Django 3.1.7 on 2021-04-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_subscriber'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('email_to', 'author_id')},
        ),
    ]
