# Generated by Django 3.1.7 on 2021-04-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210410_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('time_execution', models.FloatField(verbose_name='time_exec')),
                ('path', models.CharField(max_length=100, verbose_name='path')),
                ('utm', models.CharField(max_length=100, verbose_name='utm')),
                ('ip', models.CharField(max_length=15, verbose_name='ip')),
            ],
        ),
    ]
